######################################################################
# Automatically generated by qmake (3.0) Tue Jun 14 23:31:17 2016
######################################################################

TEMPLATE = app
TARGET = 03_minimum_widget_events
INCLUDEPATH += .

QT += widgets core gui

# Input
SOURCES += main.cpp
