######################################################################
# Automatically generated by qmake (3.0) Tue Jun 14 22:41:24 2016
######################################################################

TEMPLATE = app
TARGET = 01_minimum
INCLUDEPATH += .

QT       += widgets

# Input
SOURCES += main.cpp
