######################################################################
# Automatically generated by qmake (3.0) Tue Jun 14 22:48:50 2016
######################################################################

TEMPLATE = app
TARGET = 01_minimum_event
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
