######################################################################
# Automatically generated by qmake (3.0) Fri Jun 17 00:31:46 2016
######################################################################

TEMPLATE = app
TARGET = 05_minimum_ui
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += askdlg.h ui_askdlg.h
FORMS += askdlg.ui
SOURCES += askdlg.cpp main.cpp
