######################################################################
# Automatically generated by qmake (3.0) Wed Jun 15 01:27:07 2016
######################################################################

TEMPLATE = app
TARGET = 04_minimum_moc
INCLUDEPATH += .

QT += widgets
CONFIG += c++11

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp
