######################################################################
# Automatically generated by qmake (3.0) Wed Jun 29 20:04:26 2016
######################################################################

TEMPLATE = app
TARGET = 00_console
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
